---
---

window.jonny = window.jonny || {}
window.jonny.activateOnScroll = ->
window.isMobile = ( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent))

# Preload images
window.jonny.preloadImages = ->
  $('[data-image]').each (i, elem) ->
    $elem = $(elem)
    url = $elem.attr('data-image')
    if url == null or url.length <= 0
      return
    $elem.addClass 'image-loading'
    $('<img/>').attr('src', url).load ->
      $(this).remove()
      $elem.css 'background-image', 'url(' + url + ')'
      $elem.removeClass 'image-loading'
      $elem.addClass 'image-ready'

window.jonny.activateOnScroll = (scrollPos) ->
  $activateOnScroll = $('.activate-on-scroll')
  $activateOnScreen = $('.activate-on-screen')

  # console.log scrollPos
  if isMobile
    $activateOnScroll.each (i, elem) ->
      $(elem).addClass 'active'
    $activateOnScreen.each (i, elem) ->
      $(elem).addClass 'active'
    window.jonny.activateOnScroll = ->
      return
  else
    windowHeight = $(window).height()
    $activateOnScroll.each (i, elem) ->
      $elem = $(elem)
      pos = Math.round($elem.offset().top) - windowHeight * 0.5
      # console.log scrollPos, pos
      if scrollPos > pos
        $elem.removeClass 'activate-on-scroll'
        $elem.addClass 'active'

    $activateOnScreen.each (i, elem) ->
      $elem = $(elem)
      pos = Math.round($elem.offset().top) - windowHeight * 0.9
      if scrollPos > pos
        $elem.addClass 'active'


    # $projects.each (i, elem) ->
    #   $elem = $(elem)
    #   pos = Math.round($elem.offset().top) - windowHeight * 0.7
    #   if scrollPos > pos && scrollPos < (pos + $elem.height())
    #     $elem.removeClass 'activate-on-scroll'
    #     $elem.addClass 'active'

# Paralax
# Cross-browser way to get the current scroll position
getScrollPosition = ->
  if document.documentElement.scrollTop == 0
    document.body.scrollTop
  else
    document.documentElement.scrollTop

# $project = $('.header-content')
# $projectBg = $('.header-background')
# windowHeight = window.screen.availHeight
# opacity = 1
# oldScrollPos = 0
#
# # paralax = ->
# #   scrollPos = getScrollPosition()
# #   if scrollPos < windowHeight and scrollPos != oldScrollPos
# #     $project.each (i, el) ->
# #       opacity = 1 - ((scrollPos - (.15 * windowHeight)) / (0.85 * windowHeight))
# #       oldScrollPos = scrollPos
# #       offset = scrollPos / 5
# #       s = headBg.style
# #       transform = 'translateY(' + offset + 'px' + ') translateZ(0)'
# #       s.webkitTransform = transform
# #       s.MozTransform = transform
# #       #cap first letter
# #       s.msTransform = transform
# #       s.OTransform = transform
# #       #cap first letter
# #       s.transform = transform

$ ->
  window.jonny.activateOnScroll()
  window.jonny.preloadImages()

window.jonny = window.jonny || {}

window.requestAnimFrame = do ->
  window.requestAnimationFrame or window.webkitRequestAnimationFrame or window.mozRequestAnimationFrame or (callback) ->
    window.setTimeout callback, 500
    return

render = ->
  scrollPos = $(document).scrollTop()
  jonny.activateOnScroll scrollPos
  #paralax()
  return

`$( document ).ready( function () {
	( function animloop() {
		window.requestAnimFrame( animloop );
		render();
	} )();
} );`

# ---
# generated by js2coffee 2.0.3
